---
namespace: ericsysmin
name: docker
version: "1.0.0"
readme: README.md
authors:
  - Eric Anderson <eric.sysmin@gmail.com>
description: Docker collection
license_file: LICENSE
tags:
  - docker
  - infrastructure
dependencies: {
  "community.general": "*",
  "ansible.posix": "*"
}
repository: https://github.com/ericsysmin/ansible-collection-docker
homepage: https://github.com/ericsysmin/ansible-collection-docker
issues: https://github.com/ericsysmin/ansible-collection-docker/issues
