---
# code: language=ansible
# tasks file for docker_systemd_service

- name: Docker systemd service | Deploy the service
  ansible.builtin.template:
    src: docker_systemd_service.service.j2
    dest: /etc/systemd/system/{{ docker_systemd_service_name }}.service
    mode: "0644"
  register: docker_systemd_service_file
  notify:
    - Docker systemd service | Services | Daemon reload
    - Docker systemd service | Services | Restart service

- name: Docker systemd service | Enable and Start the service
  ansible.builtin.systemd:
    name: "{{ docker_systemd_service_name }}"
    enabled: "{{ docker_systemd_service_enabled }}"
    state: "{{ docker_systemd_service_start | ternary('started', omit) }}"
