---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Upgrade python # noqa package-latest
      ansible.builtin.package:
        name: python
        state: latest
    - name: Create containerd folder
      ansible.builtin.file:
        path: /etc/systemd/system/containerd.service.d
        state: directory
        mode: "0644"
      when: ansible_service_mgr == "systemd"
    - name: Override file for containerd
      ansible.builtin.copy:
        src: files/override.conf
        dest: /etc/systemd/system/containerd.service.d/override.conf
        mode: "0644"
      when: ansible_service_mgr == "systemd"
  roles:
    - role: ericsysmin.docker.docker
