---
# code: language=ansible
- name: Docker | EE | APT | Install Prerequisits for APT
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Docker | EE | APT | Perform specific os tasks
  ansible.builtin.include_tasks: os/{{ ansible_distribution | lower }}.yml

- name: Docker | EE | APT | Remove old repo lxc-docker
  ansible.builtin.apt:
    name:
      - lxc-docker
      - docker
      - docker-engine
      - docker-ce
    state: absent
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Docker | EE | APT | Install Docker Engine
  ansible.builtin.apt:
    name: docker-ee
    state: present
  notify: Docker | Restart Docker
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
