---
# code: language=ansible
- name: Docker | EE | Store Docker EE repository URL
  ansible.builtin.copy:
    content: "{{ docker_ee_url }}"
    dest: /etc/yum/vars/dockerurl
    mode: "0644"

- name: Docker | EE | YUM | Install yum-utils
  ansible.builtin.yum:
    name: yum-utils
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Docker | EE | YUM | Deploy repository
  ansible.builtin.command: yum-config-manager --add-repo {{ docker_ee_url }}/docker-ee.repo
  args:
    creates: /etc/yum.repos.d/docker-ee.repo

- name: Docker | EE | YUM | Perform specific os tasks
  ansible.builtin.include_tasks: os/{{ ansible_distribution | lower }}.yml

- name: Docker | EE | YUM | Install Docker Application
  ansible.builtin.yum:
    name: docker-ee
    state: present
  notify: Docker | Restart Docker
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
