---
# code: language=ansible
# tasks file for docker
- name: Check ansible version
  when:
    - ansible_version.full is version('2.4', '<')
  ansible.builtin.debug:
    msg: >-
      "This role works best with ansible version 2.4 or greater.
      It is recommended to use the latest ansible version for the best experience."

- name: Docker | Manage OS not supported by docker-ce
  ansible.builtin.fail:
    msg: This OS is not supported by Docker-CE, and therefor not supported by this role.
  when: docker_edition == "ce" and
    (ansible_distribution | lower == "centos" and ansible_distribution_major_version == "6") or
    ansible_distribution | lower == "redhat" or
    ansible_distribution | lower == "oraclelinux"

- name: Docker | Include distribution specific variables | {{ ansible_distribution }}
  ansible.builtin.include_vars: ansible_distribution/{{ ansible_distribution.split(' ', 1)[0] | lower }}.yml

- name: Docker | Include OS Family specific variables | {{ ansible_os_family }}
  ansible.builtin.include_vars: ansible_os_family/{{ ansible_os_family.split(' ', 1)[0] | lower }}.yml

- name: Docker | EE | Check Requirements
  ansible.builtin.fail:
    msg: Variable docker_ee_url is required and is not defined.
  when:
    - docker_ee_url is not defined
    - docker_edition == "ee"

- name: Docker | Storage Driver
  ansible.builtin.include_tasks: storage_drivers/{{ docker_storage_driver }}.yml
  when: docker_storage_driver is defined

- name: Docker | Start Installation
  ansible.builtin.include_tasks: "{{ docker_edition }}/{{ ansible_pkg_mgr }}.yml"
  when: docker_repo == "docker"

- name: Docker | Start Installation | Other repo
  ansible.builtin.include_tasks: other_repo.yml
  when: docker_repo == "other"

- name: Docker | Ensure service starts at boot
  ansible.builtin.service:
    name: docker
    enabled: "{{ docker_service_enabled }}"

- name: Docker | Deploy Config
  ansible.builtin.include_tasks: deploy_config.yml
- name: Docker | Proxy configuration
  ansible.builtin.include_tasks: proxy.yml
  when: docker_http_proxy is defined or docker_https_proxy is defined or docker_no_proxy_params is defined

- name: Docker | Add users to docker group
  ansible.builtin.include_tasks: docker_users.yml
  when: docker_users is defined

- name: Docker | Ensure service started
  ansible.builtin.service:
    name: docker
    state: started
