---
# code: language=ansible
- name: Docker | Start Installation | Other repo
  ansible.builtin.package:
    name: docker-{{ docker_edition }}
  when:
    - docker_repo == "other"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
