---
# code: language=ansible
argument_specs:
  main:
    short_description: Ansible role to install and configure Docker
    description:
      - Installation of Docker following Docker-Engine install procedures as documented by Docker.
      - It will manage kernel versions as well, verifying the that the correct kernel for Docker support is installed.
    author:
      - Eric Anderson
    options:
      docker_edition:
        description: Specifies either ce, or ee edition of Docker.
        default: ce
      docker_ee_url:
        description: Docker EE URL from the Docker Store
      docker_repo:
        description:
          - Defines how Ansible manages the repository
          - Options are C(other) and C(docker)
        default: docker
      docker_channel:
        description: What release channel of Docker to install.
        default: stable
      docker_ee_version:
        description: Docker EE version for EE repository
        default: 17.03
      docker_storage_driver:
        description: Storage driver to use
      docker_block_device:
        description: The device name used for the storage driver.
      docker_mount_opts:
        description: The mount options when mounting filesystems
      docker_storage_opts:
        description: Storage driver options
      docker_api_cors_header:
        description: Set CORS headers in the remote API
      docker_authorization_plugins:
        description: Authorization plugins to load
      docker_bip:
        description: Specify network bridge IP
      docker_bridge:
        description: Attach containers to a network bridge
      docker_cgroup_parent:
        description: Set parent cgroup for all containers
      docker_cluster_store:
        description: Set cluster store options
      docker_cluster_store_opts:
        description: Please see dockerd manual for info
      docker_cluster_advertise:
        description: Address or interface name to advertise
      docker_debug:
        description: Enable debug mode
      docker_default_gateway:
        description: Container default gateway IPv4 address
      docker_default_gateway_v6:
        description: Container default gateway IPv6 address
      docker_default_runtime:
        description: Default OCI runtime for containers
      docker_default_ulimits:
        description: Default ulimits for containers
      docker_disable_legacy_registry:
        description: Disable contacting legacy registries
      docker_dns:
        description: DNS server to use
      docker_dns_opts:
        description: DNS options to use
      docker_dns_search:
        description: DNS search domains to use
      docker_exec_opts:
        description: Runtime execution options
      docker_exec_root:
        description: Root directory for execution state files
      docker_fixed_cidr:
        description: IPv4 subnet for fixed IPs
      docker_fixed_cidr_v6:
        description: IPv6 subnet for fixed IPs
      docker_graph:
        description: Root of the Docker runtime
      docker_group:
        description: Group for the unix socket
      docker_hosts:
        description: Daemon socket(s) to connect to
      docker_icc:
        description: Enable inter-container communication
      docker_insecure_registries:
        description: Enable insecure registry communication
      docker_ip:
        description: Default IP when binding container ports
      docker_iptables:
        description: Enable addition of iptables rules
      docker_ipv6:
        description: Enable IPv6 networking
      docker_ip_forward:
        description: Enable net.ipv4.ip_forward
      docker_ip_masq:
        description: Enable IP masquerading
      docker_labels:
        description: Set key=value labels to the daemon
      docker_live_restore:
        description: Enables keeping containers alive during daemon downtime
      docker_log_driver:
        description: Default driver for container logs
      docker_log_level:
        description: Set the logging level
      docker_log_opts:
        description: Default log driver options for containers
      docker_max_concurrent_downloads:
        description: Set the max concurrent downloads for each pull
      docker_max_concurrent_uploads:
        description: Set the max concurrent uploads for each push
      docker_mtu:
        description: Set the containers network MTU
      docker_oom_score_adjust:
        description: Set the oom_score_adj for the daemon
      docker_pidfile:
        description: Path to use for daemon PID file
      docker_raw_logs:
        description: Full timestamps without ANSI coloring
      docker_registry_mirrors:
        description: Preferred Docker registry mirror
      docker_runtimes:
        description: Register an additional OCI compatible runtime
      docker_selinux_enabled:
        description: Enable selinux support
      docker_swarm_default_advertise_addr:
        description: Set default address or interface for swarm advertised address
      docker_tls:
        description: Use TLS; implied by –tlsverify
      docker_tlscacert:
        description: Trust certs signed only by this CA
      docker_tlscert:
        description: Path to TLS certificate file
      docker_tlskey:
        description: Path to TLS key file
      docker_tlsverify:
        description: Use TLS and verify the remote
      docker_userland_proxy:
        description: Use userland proxy for loopback traffic
      docker_userns_remap:
        description: User/Group setting for user namespaces
      docker_users:
        description: A list of system users to be added to the docker group (so they can use Docker on the server)
      docker_http_proxy:
        description: Set the Docker service to use HTTP_PROXY
      docker_https_proxy:
        description: Set the Docker service to use HTTPS_PROXY
      docker_no_proxy_params:
        description: Do not proxy for Docker service params
